#!/usr/bin/env python

import math
import rospy
from geometry_msgs.msg import Point
from controller.srv import *


class Controller(object):
    def __init__(self):
        rospy.init_node('controller')
        # start the service 
        self.service = rospy.Service('~control_command', ControlCommand,
                                self.handle_control_command)
        # define the publisher
        self.command_pub = rospy.Publisher('/controller/ctrl_cmd',
                                       Point, queue_size=1)
        rospy.spin()

    def handle_control_command(self,req):
        self.command_pub.publish(req)
        return ControlCommandResponse(True)

if __name__ == '__main__':
    try:
        Controller()
    except rospy.ROSInterruptException:
        pass
